server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3310/user_db?useSSL=false
    username: user_user
    password: user_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  jwtSecret: "mockSecret"
  jwtExpiration: 86400000